# Docker file for basic server functionality
# Update to latest Ubuntu packages, install my basic stuff

FROM ubuntu:trusty
MAINTAINER "Joe Moore" jpvlsmv@gmail.com

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get -y dist-upgrade
